using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CyreneMvvm.SourceGenerator;

[Generator]
public class ObservableGenerator : ISourceGenerator
{
    private class SyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> CandidateClasses { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
                classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                CandidateClasses.Add(classDeclaration);
        }
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not SyntaxReceiver receiver) return;

        foreach (var candidateClass in receiver.CandidateClasses)
        {
            var model = context.Compilation.GetSemanticModel(candidateClass.SyntaxTree);
            var classSymbol = model.GetDeclaredSymbol(candidateClass);
            if (classSymbol == null || !GeneratorHelper.IsObObject(classSymbol)) continue;

            var source = Generate(context, classSymbol, candidateClass, model);
            if (string.IsNullOrEmpty(source)) continue;

            context.AddSource($"{classSymbol.Name}_Observable.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string Generate(GeneratorExecutionContext context, INamedTypeSymbol classSymbol, ClassDeclarationSyntax classSyntax, SemanticModel model)
    {
        var props = new List<PropertyDeclarationSyntax>();
        var collections = new List<PropertyDeclarationSyntax>();
        foreach (var prop in classSyntax.Members.OfType<PropertyDeclarationSyntax>())
        {
            var propSymbol = model.GetDeclaredSymbol(prop);
            if (propSymbol == null) continue;

            if (GeneratorHelper.HasObIgnoreAttr(prop, model)) continue;
            if (!GeneratorHelper.IsSupportedType(propSymbol.Type))
            {
                context.ReportDiagnostic(Diagnostic.Create(GeneratorHelper.UnsupportedType, prop.GetLocation(),
                    propSymbol.Name, propSymbol.Type.ToDisplayString()));
                continue;
            }

            if (GeneratorHelper.IsObCollection(prop, model)) collections.Add(prop);
            else props.Add(prop);
        }
        if (props.Count == 0 && collections.Count == 0) return "";

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var space = classSymbol.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(space))
        {
            sb.AppendLine($"namespace {space};");
            sb.AppendLine();
        }

        var modifiers = string.Join(" ", classSyntax.Modifiers.Select(m => m.Text));
        sb.AppendLine($"{modifiers} class {classSymbol.Name}");
        sb.AppendLine("{");

        foreach (var prop in props)
        {
            var propSymbol = model.GetDeclaredSymbol(prop);
            if (propSymbol == null) continue;
            sb.AppendLine(GeneratorHelper.ShouldGenShadow(classSymbol, propSymbol) ? GenerateIgnoreProperty(propSymbol) : GenerateProperty(propSymbol));
        }

        foreach (var collection in collections)
        {
            var propSymbol = model.GetDeclaredSymbol(collection);
            if (propSymbol == null) continue;
            sb.AppendLine(GeneratorHelper.ShouldGenShadow(classSymbol, propSymbol) ? GenerateIgnoreCollection(propSymbol) : GenerateCollection(propSymbol));
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GenerateIgnoreAttribute(IPropertySymbol propSymbol)
    {
        if (GeneratorHelper.IsPrimary(propSymbol.Type)) return "";
        return "    [global::FreeSql.DataAnnotations.Column(IsIgnore = true)]";
    }

    private string GenerateProperty(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var propType = propSymbol.Type.ToDisplayString();
        var isRef = propSymbol.Type.IsReferenceType && propSymbol.Type.SpecialType != SpecialType.System_String;

        var sb = new StringBuilder();

        sb.AppendLine($"    private void _On{propName}Changed()");
        sb.AppendLine("    {");
        sb.AppendLine($"        OnPropertyChanged(nameof({propName}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        if (isRef) sb.AppendLine($"            if (field is global::{GeneratorHelper.INotifyCallback} r) r.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine("            return field;");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("            {");
        if (isRef) sb.AppendLine($"                if (field is global::{GeneratorHelper.INotifyCallback} u) u.UnregisterParent(this);");
        sb.AppendLine("                field = value;");
        if (isRef) sb.AppendLine($"                if (field is global::{GeneratorHelper.INotifyCallback} r) r.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine($"                _On{propName}Changed();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        return sb.ToString();
    }

    private string GenerateIgnoreProperty(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var propType = propSymbol.Type.ToDisplayString();
        var fieldName = $"{char.ToLower(propName[0])}{propName.Substring(1)}";
        var lockName = $"{fieldName}Lock";
        var flagName = $"{fieldName}Flag";
        var isRef = propSymbol.Type.IsReferenceType && propSymbol.Type.SpecialType != SpecialType.System_String;

        var sb = new StringBuilder();

        sb.AppendLine($"    private readonly object {lockName} = new();");
        sb.AppendLine($"    private bool {flagName};");
        sb.AppendLine();

        sb.AppendLine($"    private void _On{propName}Changed()");
        sb.AppendLine("    {");
        sb.AppendLine($"        OnPropertyChanged(nameof({propName}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine(GenerateIgnoreAttribute(propSymbol));
        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        if (isRef) sb.AppendLine($"                if (field is global::{GeneratorHelper.INotifyCallback} r) r.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine("                return field;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine("            var notify = false;");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("                {");
        if (isRef) sb.AppendLine($"                    if (field is global::{GeneratorHelper.INotifyCallback} u) u.UnregisterParent(this);");
        sb.AppendLine("                    field = value;");
        if (isRef) sb.AppendLine($"                    if (field is global::{GeneratorHelper.INotifyCallback} r) r.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine($"                    notify = !{flagName};");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine($"            if (notify) _On{propName}Changed();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.Append(GenerateShadowProperty(propSymbol));

        return sb.ToString();
    }

    private string GenerateCollection(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var propType = propSymbol.Type.ToDisplayString();
        var nullable = propSymbol.Type.NullableAnnotation == NullableAnnotation.Annotated;

        var sb = new StringBuilder();

        sb.AppendLine($"    private void _On{propName}Changed()");
        sb.AppendLine("    {");
        sb.AppendLine($"        OnPropertyChanged(nameof({propName}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            {(nullable ? "if (field != null) " : "")}field.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine("            return field;");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (field != null) field.UnregisterParent(this);");
        sb.AppendLine("                field = value;");
        sb.AppendLine($"                {(nullable ? "if (field != null) " : "")}field.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine($"                _On{propName}Changed();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        return sb.ToString();
    }

    private string GenerateIgnoreCollection(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var propType = propSymbol.Type.ToDisplayString();
        var fieldName = $"{char.ToLower(propName[0])}{propName.Substring(1)}";
        var lockName = $"{fieldName}Lock";
        var flagName = $"{fieldName}Flag";
        var nullable = propSymbol.Type.NullableAnnotation == NullableAnnotation.Annotated;

        var sb = new StringBuilder();

        sb.AppendLine($"    private readonly object {lockName} = new();");
        sb.AppendLine($"    private bool {flagName};");
        sb.AppendLine();

        sb.AppendLine($"    private void _On{propName}Changed()");
        sb.AppendLine("    {");
        sb.AppendLine($"        OnPropertyChanged(nameof({propName}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine(GenerateIgnoreAttribute(propSymbol));
        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        sb.AppendLine($"                {(nullable ? "if (field != null) " : "")}field.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine("                return field;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine("            var notify = false;");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (field != null) field.UnregisterParent(this);");
        sb.AppendLine("                    field = value;");
        sb.AppendLine($"                    {(nullable ? "if (field != null) " : "")}field.RegisterParent(this, _On{propName}Changed);");
        sb.AppendLine($"                    notify = !{flagName};");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine($"            if (notify) _On{propName}Changed();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.Append(GenerateShadowProperty(propSymbol));

        return sb.ToString();
    }

    private string GenerateShadowProperty(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var fieldName = $"{char.ToLower(propName[0])}{propName.Substring(1)}";
        var lockName = $"{fieldName}Lock";
        var flagName = $"{fieldName}Flag";

        var sb = new StringBuilder();

        sb.AppendLine();
        sb.AppendLine($"    [global::FreeSql.DataAnnotations.Column(Name = \"{propName}\", StringLength = -1)]");
        sb.AppendLine("    [global::System.Text.Json.Serialization.JsonIgnore]");
        sb.AppendLine($"    public string {propName}_JsonShadow");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        sb.AppendLine($"                return global::CyreneMvvm.Config.ObColumnConfig.Parser?.Serialize({propName}) ?? string.Empty;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            lock ({lockName})");
        sb.AppendLine("            {");
        sb.AppendLine($"                {flagName} = true;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var de = global::CyreneMvvm.Config.ObColumnConfig.Parser?.Deserialize<{propSymbol.Type}>(value);");
        sb.AppendLine($"                    if (de != null) {propName} = de;");
        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine($"                    {flagName} = false;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        return sb.ToString();
    }
}
