using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CyreneMvvm.SourceGenerator;

[Generator]
public class ObservableGenerator : ISourceGenerator
{
    private class SyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> CandidateClasses { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
                classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                CandidateClasses.Add(classDeclaration);
        }
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not SyntaxReceiver receiver) return;

        foreach (var candidateClass in receiver.CandidateClasses)
        {
            var model = context.Compilation.GetSemanticModel(candidateClass.SyntaxTree);
            var classSymbol = model.GetDeclaredSymbol(candidateClass);
            if (classSymbol == null || !GeneratorHelper.IsObservableObject(classSymbol)) continue;

            var source = Generate(classSymbol, candidateClass, model);
            if (string.IsNullOrEmpty(source)) continue;

            context.AddSource($"{classSymbol.Name}_Observable.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string Generate(INamedTypeSymbol classSymbol, ClassDeclarationSyntax classSyntax, SemanticModel model)
    {
        var props = new List<PropertyDeclarationSyntax>();
        var collections = new List<PropertyDeclarationSyntax>();
        foreach (var prop in classSyntax.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (GeneratorHelper.ShouldGenProp(prop, model)) props.Add(prop);
            if (GeneratorHelper.ShouldGenCollection(prop, model)) collections.Add(prop);
        }
        if (props.Count == 0 && collections.Count == 0) return "";

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var space = classSymbol.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(space))
        {
            sb.AppendLine($"namespace {space};");
            sb.AppendLine();
        }

        var modifiers = string.Join(" ", classSyntax.Modifiers.Select(m => m.Text));
        sb.AppendLine($"{modifiers} class {classSymbol.Name}");
        sb.AppendLine("{");

        foreach (var prop in props)
        {
            var propSymbol = model.GetDeclaredSymbol(prop);
            if (propSymbol == null) continue;
            sb.AppendLine(GenerateProperty(propSymbol));
        }

        foreach (var collection in collections)
        {
            var propSymbol = model.GetDeclaredSymbol(collection);
            if (propSymbol == null) continue;
            sb.AppendLine(GenerateCollection(propSymbol));
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GenerateProperty(IPropertySymbol propSymbol)
    {
        var propType = propSymbol.Type.ToDisplayString();

        var sb = new StringBuilder();

        sb.AppendLine($"    public partial {propType} {propSymbol.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        get;");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("            {");
        sb.AppendLine("                field = value;");
        sb.AppendLine("                OnPropertyChanged();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        return sb.ToString();
    }

    private string GenerateCollection(IPropertySymbol propSymbol)
    {
        var propName = propSymbol.Name;
        var propType = propSymbol.Type.ToDisplayString();
        var nullable = propSymbol.Type.NullableAnnotation == NullableAnnotation.Annotated;

        var sb = new StringBuilder();

        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            {(nullable ? "if (field != null) " : "")}field.RegisterParentProp(OnPropertyChanged, nameof({propName}));");
        sb.AppendLine("            return field;");
        sb.AppendLine("        }");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!global::System.Collections.Generic.EqualityComparer<{propType}>.Default.Equals(field, value))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (field != null) field.UnregisterParentProp();");
        sb.AppendLine("                field = value;");
        sb.AppendLine("                OnPropertyChanged();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        return sb.ToString();
    }
}
